name: Build Gradle and test feature branch

on:
  push:
    branches:
    - feature/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean test

      - name: Archive Serenity Report
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: serenity-report
          path: target/site/serenity