name: Build Gradle and test feature branch

on:
  push:
    branches:
    - feature/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew

      - name: Build with Gradle
        run: |
          ./gradlew clean test
          echo "Build with Gradle"

      - name: Archive Gradle Report
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: Package
          path: build/libs