name: Main

on:
  push:
    branches:
      - feature/*
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit

  analyze:
    uses: ./.github/workflows/analyze.yml
    secrets: inherit