name: Main

on:
  push:
    branches:
      - feature/*
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit

  sonarqube:
    uses: ./.github/workflows/code_analyzer.yml
    secrets: inherit
    needs: [build]