name: Main

on:
  push:
    branches:
      - feature/*
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit

#  sonarqube:
#    if: github.ref == 'refs/heads/main' || github.event_name == 'pull_request'
#    uses: ./.github/workflows/code_analyzer.yml
#    secrets: inherit
#    needs: [build]