on:
  workflow_call:

jobs:
  quality_gate:
    name: Check SonarCloud Quality Gate Status
    runs-on: ubuntu-latest
    needs: sonarqube
    steps:
      - name: Check SonarCloud Quality Gate Status
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          PROJECT_KEY=<your_project_key> # Replace with your SonarCloud project key
          QUALITY_GATE_STATUS=$(curl -s -u $SONAR_TOKEN: \
            "https://sonarcloud.io/api/qualitygates/project_status?projectKey=$PROJECT_KEY" \
            | jq -r '.projectStatus.status')
          
          echo "Quality Gate Status: $QUALITY_GATE_STATUS"
          if [ "$QUALITY_GATE_STATUS" != "OK" ]; then
            echo "Quality Gate failed!"
            exit 1
          fi